export const stringConstants = {
  home: 'Home',
  appointment: 'Appointment',
  homeCardhelloText: 'Hello Aelita!',
  homeCarddDescText: 'How are you feeling today?',
  search: 'Search',
  our_service: 'Our Service',
  view_all: 'View All',
  medicine: 'Medicine',
  vaccine: 'Vaccine',
  tooth: 'Tooth Care',
  heart: 'Heart',
  our_package: 'Our Package',
  health_consultation: 'Health Consultation',
  tooth_care: 'Tooth Care',
  consultant_doc: 'Mr. John',
  tooth_doc: 'Mrs. Yumi',
  date: 'Date',
  schedule: 'Schedule',
  start_time: 'Start',
  end_time: 'End',
  complaint: 'Your Complaint',
  complaint_text: 'Type your complaint here...',
  next: 'Next',
  schedule_fixed: 'Schedule Fixed',
  onboarding_title: 'Discover Top Doctors',
  onboarding_sub_title:
    'A team of professional doctors from many hospitals help you have the best healthcare experience wherever you are.',
  other: 'other',
};
